# Stage 1: Build the application
FROM node AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Stage 2: Run the application
FROM node AS runner

WORKDIR /app

COPY --from=builder /app .

EXPOSE 5000

CMD [ "node", "index.js" ]
